ASoC: wsa881x: fix buffer overflow
Clang-r365631 is reporting:
asoc/codecs/wsa881x.c:392:9: error: 'snprintf' size argument is too
large; destination buffer has size 20, but size argument is 25
[-Werror,-Wfortify-source]

len = snprintf(tmp_buf, 25, "0x%.3x: 0x%.2x\n", i,
      ^

Since tmp_buf is only 20B, and the format string should only be 13B by
my count, use the actual ARRAY_SIZE.

Make sure to zero the buffer first, as it's passed to copy_to_user.

Prefer scnprintf which returns the amount of bytes written.

Bug: 139442076
Change-Id: I3796c702966310aa921ad8be81afba7bfd7b853c
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>