asoc: wcd_cpe_core: fix buffer overrun
clang-r365631 reports:
asoc/codecs/wcd_cpe_core.c:1981:2: error: 'snprintf' size argument is
too large; destination buffer has size 11, but size argument is 13
[-Werror,-Wfortify-source]

snprintf(proc_name, (sizeof("cpe") + sizeof("_state") +
^

It looks like proc_name is just a C string that's used/copied in
snd_info_create_card_entry(), and WCD_CPE_STATE_MAX_LEN just sets the
size of proc_name.  Simply expand WCD_CPE_STATE_MAX_LEN to fit the data
being written. Further, cpe_name and state_name have no other uses, so
simplify the format string.

The buffer size is set:
cpe -> +3
%d aka INT_MIN aka -32767 -> +6
_state -> +6
trailing '\0' -> +1
=== 16

Bug: 139442076
Change-Id: I504492b0463e89c2ab91016a3a301cb570d88628
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>