asoc: sdm660_cdc: fix -Wmisleading-indentation
Fixes:
techpack/audio/asoc/codecs/sdm660_cdc/msm-analog-cdc.c:2683:4: error:
misleading indentation; statement is not part of the previous 'else'
[-Werror,-Wmisleading-indentation]
msm_anlg_cdc_set_micb_v(codec);
^
techpack/audio/asoc/codecs/sdm660_cdc/msm-analog-cdc.c:2679:5: note:
previous statement is here
} else
  ^

This is a functional change and should be carefully reviewed.  Based on
the indentation, it looks this the missing curly braces was
unintentional. At worst, when the condition was true, the same value was
being set again with an extra delay.

Bug: 155426751
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: Ia4b48541aebb7de14daa58e30b25bd7f71ecec9b